### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by RMajewski** [RMajewski/testsuite#57]
- [ ] App: new configuration dialog for check source config
- App: change configuration dialog for global config
  - [ ] add todo list

- Insert or change of the tests for the app:
  - [ ] Tests for global configuration dialog
- Insert or change of the tests for the testsuite core
- Insert or change of the tests for the check source
